config:
    ## Main plugin configurations
    main:
        ## The time is set by hours (DECIMALS ALLOWED)
        inverval: 6
        ## !!!! IMPORTANT !!!!
        ## If your server is running under MultiCraft, set this to true!
        ## Go into "Scheduled Tasks", and configure MultiCraft to restart the server, the same time your server will restart.
        ## /autore pause, /autore start, /autore now, /autore reload, /autore in, and max-players feature will be disabled with MutliCraft.
        ## Since these commands, and features alters the timer in AutoRestart, MultiCraft timer is still running.
        mutlicraft: false
        ## The shutdown message on when the server restarts.
        ## Color codes now enabled! Use regular chat colors!
        shutdown: '&cServer Restarting! We will be back up any minute!'

    ## Reminder Settings
    reminder:
        ## Enable or disable reminders
        enabled:
            minutes: true
            seconds: true
        ## Sets the reminder time for when to show reminders
        timer:
            ## Reminder is set by minutes
            ## This will show how much time before the restart to notify players when the server
            ## will restart!
            minutes:
            - 15
            - 10
            - 5
            - 1
            ## This is saying when should the plugin start counting down the seconds for a server restart?
            ## This is not like the minute reminders. If you set to 5, it'll start saying the "seconds message"
            ## every second, STARTING AT 5 seconds before restart!
            seconds:  5

    broadcast:
        ## Enable or Disable the broadcast
        enabled:
            ## Show the broadcast on the minute reminders!
            minutes: true
            ## Show the broadcast on the last seconds of a server restart!
            seconds: true
            ## Show the broadcast when type /autore time
            time: true
            ## Show the broadcast when typed /autore start or /autore pause
            status: true
            ## Show the broadcast when the server time has been changed!
            change: true
        ## The configuration for broadcast messages
        messages:
            ## Prefix for broadcast, this is applied to (minutes, seconds, time, status, and change)
            prefix: '&f[&7AutoRestart&f] &e'
            ## %m - minutes
            minutes: 'Server Will Restart In %m Minutes!'
            ## %s - seconds
            seconds: 'Server is restarting in %s Seconds!'
            ## %h - hours, %m - minutes, %s - seconds
            time: '&cServer restarting in &f%h&cH &f%m&cM &f%s&cS!'
            ## There are no tags for this section.
            status:
                start: '&cAutoRestart timer has been started!'
                pause: '&cAutoRestart timer has been paused'
            ## %h - hours, %m - minutes, %s - seconds
            change: '&cServer now is restarting in &f%h&cH &f%m&cM &f%s&cS!'

    popups:
        ## Enable or Disable the 1.8 Popups!
        enabled:
            ## Show the pop ups on the minute reminders!
            minutes: true
            ## Show the pop ups on the last seconds of a server restart!
            seconds: true
            ## Show the pop ups when type /autore time
            time: true
            ## Show the pop ups when typed /autore start or /autore pause
            status: true
            ## Show the pop ups when the server time has been changed!
            change: true
        ## This section is for the customization of the popup messages!
        messages:
            minutes: ## %m - minutes
                title: '&cServer Restarting In'
                subtitle: '&f%m &cMinutes!'
            seconds: ## %s - seconds
                title: '&cServer Restarting In'
                subtitle: '&f%s &cSeconds!'
            time: ## %h - hours, %m - minutes, %s - seconds
                title: '&cServer Restarting In'
                subtitle: '&f%h&cH &f%m&cM &f%s&cS!'
            status: ## There are no tags for this section
                start:
                    title: '&cAutoRestart has been started!'
                    subtitle: ''
                pause:
                    title: '&cAutoRestart has been paused!'
                    subtitle: ''
            change: ## %h - hours, %m - minutes, %s - seconds
                title: '&cServer Restarting In'
                subtitle: '&f%h&cH &f%m&cM &f%s&cS!'
    
    ## This section is to edit the timing for the popups, these are set in ticks!
    ## To understand ticks. 1 second is relevent to 20 ticks! So a second and a half (1.5s) is 30 ticks!
    ## Fadein, stay, fadeout are the 3 arguments. You can edit how long it takes to fadein, fadeout etc.
    ## You can also put the fade numbers to 0, and then the popup's will be instant!
    ## Also you can edit the delay, to make the title popup, and then the subtitle half a second later.
    ## Get creative!
    timings:
        minutes:
            title:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
            subtitle:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
        seconds:
            title:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
            subtitle:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
        time:
            title:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
            subtitle:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
        status-start:
            title:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
            subtitle:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
        status-pause:
            title:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
            subtitle:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
        change:
            title:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20
            subtitle:
                delay: 0
                fadein: 20
                stay: 40
                fadeout: 20

    ## This section will allow you to run Console Commands before a given amount of seconds
    commands:
        ## This will allow you to enabled, or disable the last second commands.
        enabled: false
        ## This is when the commands will be executed. IN SECONDS
        time: 5
        ## List of commands to execute
        commands:
        - '/place your commands'
        - '/in this fasion'

     ## This will stop your server from shutting down if you have more than X amount of players configured in "amount".
    max-players:
        ## Enable or Disable this feature
        enabled: false
        ## The max amount of players allow for a restart. If you set this to 10, and your server has 11 people online
        ## your server will not shutdown until there is 10 or less amount of players.
        amount: 10
        ## The delay for the server to restart after restart cancel. In seconds!
        delay: 10
        ## Message settings
        messages:
            ## The message broadcasted when too many players are online on restart!
            ## %a - amount
            alert: '&bToo many players online for restart. Max &f%a&b amount of players allowed for a restart. Waiting people leave!'
            ## This message appears when the amount of players are met after restart cancel!
            ## %d - delay
            shutdown: '&aServer now restarting in &f%d&a seconds!'
        
## DO NOT CHANGE THIS!!!!
version: 12