name: AutoRestart
version: 2.8.1
main: org.serversmc.autorestart.core.Main
author: ServersMC, DennisLysenko
commands:
    autore:
        description: 'Main AutoRestart command.'
        usage: '/autore help'