name: AutoRestart
version: 3.0.0
main: org.serversmc.autorestart.core.Main
author: ServersMC, DennisLysenko
commands:
    autore:
        description: 'Main AutoRestart command.'
        usage: '/autore help'